services:
  swagger:
    image: swaggerapi/swagger-ui:latest
    environment:
      - API_URL=https://api.localhost/
    restart: unless-stopped

  mail:
    image: maildev/maildev
    restart: unless-stopped
