set dotenv-load

default:
  just --list

make-project:
  rm app
  ln -sf .. app
  cp -rP app.sample/* app/
  cp -rP app.sample/.env app/
  cp -rP app.sample/.gitignore app/
  rm llw
  ln -sf . llw
  cd .. ; rm llw ; ln -sf lazy-lob-web llw

init:
  docker compose exec web npm install
  docker compose exec web dbmate up
  just migrate

init-dev: init
  sudo trust anchor ./app/data/web/pki/authorities/local/root.crt
  sudo update-ca-trust

reinit: stop
  sudo rm -fR app.sample/data/*
  touch app.sample/migrations/t.sql
  rm -f app.sample/migrations/*sql
  just build
  just boot
  sleep 2; just init-dev

boot:
  docker compose up &

start: boot
  xdg-open https://localhost

build:
  docker compose build

stop:
  docker compose down

reload-caddy-config:
  just make-caddyfile
  docker compose exec web caddy reload --config /etc/caddy/Caddyfile

reload:
  just reload-caddy-config

reboot:
  just stop
  just boot

shell service:
  docker compose exec {{service}} /bin/sh

command service command:
  docker compose exec {{service}} {{command}}

open-swagger:
  xdg-open https://swagger.localhost

open-api:
  xdg-open https://api.localhost

open:
  xdg-open https://localhost

migrate:
  just command web migrate

make-caddyfile:
  just command web make-caddyfile

logs service:
  docker compose logs {{service}} -f --tail 0

pg:
  docker compose exec db psql -U $POSTGRES_USER $POSTGRES_DB
