-- migrate:up
CREATE USER $DB_ANON_ROLE;
GRANT USAGE ON SCHEMA $DB_SCHEMA TO $DB_ANON_ROLE;
ALTER DEFAULT PRIVILEGES IN SCHEMA $DB_SCHEMA GRANT SELECT ON TABLES TO $DB_ANON_ROLE;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA $DB_SCHEMA TO $DB_ANON_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA $DB_SCHEMA TO $DB_ANON_ROLE;

-- migrate:down
REVOKE SELECT ON ALL TABLES IN SCHEMA $DB_SCHEMA FROM $DB_ANON_ROLE;
REVOKE SELECT ON ALL SEQUENCES IN SCHEMA $DB_SCHEMA FROM $DB_ANON_ROLE;
ALTER DEFAULT PRIVILEGES IN SCHEMA $DB_SCHEMA REVOKE SELECT ON TABLES FROM $DB_ANON_ROLE;
REVOKE USAGE ON SCHEMA $DB_SCHEMA FROM $DB_ANON_ROLE;
DROP USER $DB_ANON_ROLE;
